# Generated by Django 2.2.7 on 2019-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=100, null=True)),
                ('channel_thumbnail', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('stream_url', models.CharField(max_length=200)),
                ('stream_embed_url', models.CharField(max_length=200)),
                ('stream_views', models.IntegerField()),
                ('stream_thumbnail', models.CharField(max_length=100)),
                ('tof', models.IntegerField(null=True)),
                ('platform', models.IntegerField()),
            ],
        ),
    ]
