# Generated by Django 2.2.7 on 2019-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='channel_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stream',
            name='channel_thumbnail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='channel_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_embed_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_thumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
