# Generated by Django 2.2.7 on 2019-12-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
