# Generated by Django 2.2.7 on 2019-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='id',
        ),
        migrations.AlterField(
            model_name='stream',
            name='channel_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
