# Generated by Django 2.2.7 on 2019-12-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20191201_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='tof',
            field=models.IntegerField(null=True),
        ),
    ]
